mtdbt2f-4d --steps 70 --exit 700 --weight 5 200 --slant -.2 .2 --super .5 .8 --pen 0 .333 3 0 720
mtdbt2f-4d --steps 70 --exit 200 --weight 5 200 --slant -1 1 --super .1 .8 --pen 0 .333 3 0 720 --counter 700
mtdbt2f-4d --steps 70 --exit 100 --weight 5 350 --slant -1 1 --super .1 .8 --pen 0 .1 10 0 720 --counter 900